/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myexpensesswing;

/**
 *
 * @author Anar Salami
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnUsers = new javax.swing.JMenu();
        mnExpenses = new javax.swing.JMenu();
        mnExpenseType = new javax.swing.JMenu();
        mnExpenseCategory = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        menu.add(jMenu1);

        mnUsers.setText("Users");
        mnUsers.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnUsersMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        mnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsersActionPerformed(evt);
            }
        });
        menu.add(mnUsers);

        mnExpenses.setText("Expenses");
        menu.add(mnExpenses);

        mnExpenseType.setText("Expense Types");
        mnExpenseType.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnExpenseTypeMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        mnExpenseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExpenseTypeActionPerformed(evt);
            }
        });
        mnExpenseType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnExpenseTypeKeyPressed(evt);
            }
        });
        menu.add(mnExpenseType);

        mnExpenseCategory.setText("Expense Category");
        mnExpenseCategory.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnExpenseCategoryMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        menu.add(mnExpenseCategory);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnExpenseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExpenseTypeActionPerformed
        
    }//GEN-LAST:event_mnExpenseTypeActionPerformed

    private void mnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsersActionPerformed
       
    }//GEN-LAST:event_mnUsersActionPerformed

    private void mnExpenseTypeMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnExpenseTypeMenuSelected
        this.setVisible(false);
        new ExpenseTypeWindow().setVisible(true);
    }//GEN-LAST:event_mnExpenseTypeMenuSelected

    private void mnUsersMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnUsersMenuSelected
       this.setVisible(false);
       new UsersWindow().setVisible(true);
    }//GEN-LAST:event_mnUsersMenuSelected

    private void mnExpenseTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnExpenseTypeKeyPressed
        
    }//GEN-LAST:event_mnExpenseTypeKeyPressed

    private void mnExpenseCategoryMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnExpenseCategoryMenuSelected
        this.setVisible(false);
        new ExpenseCategoryWindow().setVisible(true);
    }//GEN-LAST:event_mnExpenseCategoryMenuSelected

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu mnExpenseCategory;
    private javax.swing.JMenu mnExpenseType;
    private javax.swing.JMenu mnExpenses;
    private javax.swing.JMenu mnUsers;
    // End of variables declaration//GEN-END:variables
}
